openapi: 3.0.0
info:
  title: space
  description: planets API
  version: 0.1.9

servers:
  - url: https://devjobs-vaqx.onrender.com/api
    description: space serverdd
  - url: http://localhost:3000/api
    description: local server




paths:
  /destination:
    get:
      tags:
        - destination
      responses:
        "200":
          description: Successfully fetched
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
  /crew:
    get:
      tags:
        - crew
      responses:
        "200":
          description: Successfully fetched
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
  /technology:
    get:
      tags:
        - technology
      responses:
        "200":
          description: Successfully fetched
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object