openapi: 3.0.0
info:
  title: todo
  description: todo app API
  version: 0.1.9

servers:
  - url: http://localhost:3000/api
    description: local server
  - url: https://devjobs-vaqx.onrender.com/api
    description: todo server



paths:
  /destination/{id}:
    get:
      summary: Get destination.
      parameters:
        - in: path
          name: id
          schema:
            type: integer
            minimum: 1
            maximum: 4
          required: true
          description: destination id.
      responses:
        200:
          description: succesfully.
  /crew/{id}:
    get:
      summary: Get crew.
      parameters:
        - in: path
          name: id
          schema:
            type: integer
            minimum: 1
            maximum: 4
          required: true
          description: Crew id.
      responses:
        200:
          description: succesfully
  /technology/{id}:
    get:
      summary: Get technology.
      parameters:
        - in: path
          name: id
          schema:
            type: integer
            minimum: 1
            maximum: 4
          required: true
          description: technology id
      responses:
        200:
          description: succesfully